services:
  postgres:
    image: postgres:17-alpine
    container_name: ignita-postgres-prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
    container_name: ignita-backend-prod
    restart: always
    env_file:
      - ./Backend/.env.production
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        # Build arguments required for Next.js compile-time bundling.
        # Change these to your actual domain name/public IP when deploying!
        - NEXT_PUBLIC_API_URL=http://localhost:3001
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=1056577354653-r7c3dbjr7uuiodi6osdrpj0comilu6fh.apps.googleusercontent.com
    container_name: ignita-frontend-prod
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data_prod:
