FROM node:22-alpine AS development

WORKDIR /app

RUN npm install -g pnpm
 
COPY package.json pnpm-lock.yaml ./

RUN pnpm install --ignore-scripts

COPY . .

EXPOSE 3001

CMD ["npm", "run", "start:dev"]