export enum EventCategory {
  HACKATHON = 'HACKATHON',
  INTERNSHIP = 'INTERNSHIP',
  CODING_FEST = 'CODING_FEST',
  WORKSHOP = 'WORKSHOP',
  CONTEST = 'CONTEST',
  JOB = 'JOB',
  INTERVIEW = 'INTERVIEW',
  QUIZ = 'QUIZ',
}

